/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import CommentSection from './CommentSection';
import SubmitButtons from './SubmitButtons';

interface FeedbackFormProps {
  sessionName: string;
  imageSrc: string;
}

const FeedbackForm: React.FC<FeedbackFormProps> = ({ sessionName, imageSrc }) => {
  return (
    <main className="flex flex-col justify-center py-20 bg-slate-50">
      <div className="flex flex-col items-center px-20 py-5 mt-1.5 w-full max-md:px-5 max-md:max-w-full">
        <h1 className="px-4 pt-5 pb-2 w-full text-2xl font-bold text-center max-w-[960px] text-zinc-900 max-md:max-w-full">
          How was your session with {sessionName}?
        </h1>
        <section className="flex flex-col justify-center items-start p-4 max-w-full w-[960px] max-md:pr-5">
          <img loading="lazy" src={imageSrc} alt={`Session with ${sessionName}`} className="max-w-full aspect-[5.88] w-[801px]" />
        </section>
        <CommentSection />
        <SubmitButtons />
      </div>
    </main>
  );
};

export default FeedbackForm;