/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const SubmitButtons: React.FC = () => {
  return (
    <div className="flex gap-3 px-4 py-3 mb-20 text-sm font-bold text-center whitespace-nowrap max-md:flex-wrap max-md:pr-5 max-md:mb-10">
      <button className="px-4 py-2.5 rounded-lg bg-slate-200 text-zinc-900">
        Cancel
      </button>
      <button className="px-4 py-2.5 bg-sky-500 rounded-lg text-slate-50">
        Submit
      </button>
    </div>
  );
};

export default SubmitButtons;