/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button } from "../ui/button";
import FilteredSearch from "../RegistrateSubjects/FilteredSearch";
import SearchBar from "./SearchBar";

const FilterSection: React.FC = () => {
  // const availabilityOptions = [
  //   "Hoy",
  //   "Mañana",
  //   "Esta semana",
  //   "Fines de semana",
  // ];
  const subjects = [
    "Matemáticas",
    "Mecanica",
    "Memo",
    "Memo2",
    "Memo",
    "Memo2",
    "Español",
    "Ciencia",
  ];

  return (
    <section className="flex flex-col">
      <SearchBar />

      <h2 className="mt-7 text-lg font-bold leading-6 text-neutral-900 max-md:max-w-full mb-4">
        Filtrar por materia
      </h2>
      <FilteredSearch name="" placeholder="Busca la materia" items={subjects} />
      {/* <h2 className="mt-7 text-lg font-bold leading-6 text-neutral-900 max-md:max-w-full">
        Filtrar por disponibilidad
      </h2>
      <div className="flex flex-wrap gap-3 content-start py-3 pr-4  mt-2 max-w-full text-sm font-medium leading-5 text-center text-neutral-900 w-[960px] max-md:pr-5">
        {availabilityOptions.map((option, index) => (
          <Button className="btn btn-sm " key={index}>
            {option}
          </Button>
        ))}
      </div> */}
      <Button className="btn btn-md bg-blue-600 text-white mt-4 text-ellipsis w-44">
        Aplicar filtros
      </Button>
    </section>
  );
};

export default FilterSection;
