/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TutorCard from "./TutorCard";

interface Tutor {
  name: string;
  rating: number;
  languages: string[];
  image: string;
}

const tutors: Tutor[] = [
  {
    name: "Luisa Flores",
    rating: 4.9,
    languages: ["Spanish", "English"],
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/29deb3259e23eb86a1355f9cf2a05b943dc044e561eb55ed0432799a1df4ed1b?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e",
  },
  {
    name: "Pablo Sanchez",
    rating: 4.8,
    languages: ["Spanish"],
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/b2c05535dab87e8f8470338a31b5bbf2c19288b5fb182d50c6a717f44fcb1cbe?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e",
  },
  {
    name: "Sara Johnson",
    rating: 4.7,
    languages: ["English", "Math"],
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5e345e3f144234536dc1d8833e7d31a8435339a379d78654acb6a233e43dd49f?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e",
  },
  {
    name: "John Smith",
    rating: 4.7,
    languages: ["English"],
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/182b058cf06fbe6e2c0f6b7f17ae597e2f4f0b07d3271888cef0ceec2a6dfb40?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e",
  },
  {
    name: "Maria Garcia",
    rating: 4.7,
    languages: ["Spanish"],
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4f4d19ae840da8d514010ed10947ae5298611b325dd524f54ed43e15e2c11d26?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e",
  },
];

const TutorList: React.FC = () => {
  return (
    <section className="flex flex-col  pt-4 pb-2 mt-3 w-full leading-[150%] max-w-[960px] max-md:max-w-full">
      <h2 className="text-lg font-bold leading-6 text-neutral-900 max-md:max-w-full ">
        Resultados de la búsqueda
      </h2>
      {tutors.map((tutor, index) => (
        <TutorCard key={index} tutor={tutor} />
      ))}
    </section>
  );
};

export default TutorList;
