/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import FilterSection from "./FilterSection";
import TutorList from "./TutorList";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";

const TutorSearch: React.FC = () => {
  return (
    <div className="flex flex-col justify-center bg-white w-full">
      <Header />
      <main className="flex flex-col px-3.5 mt-9 w-full max-w-[960px] mx-auto">
        <h1 className="text-3xl font-bold text-neutral-900 max-md:max-w-full">
          Encuentra un tutor
        </h1>
        <FilterSection />
        <TutorList />
      </main>
      <Pagination>
        <PaginationContent>
          <PaginationItem>
            <PaginationPrevious href="#" />
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#">1</PaginationLink>
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#" isActive>
              2
            </PaginationLink>
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#">3</PaginationLink>
          </PaginationItem>
          <PaginationItem>
            <PaginationEllipsis />
          </PaginationItem>
          <PaginationItem>
            <PaginationNext href="#" />
          </PaginationItem>
        </PaginationContent>
      </Pagination>
    </div>
  );
};

export default TutorSearch;
