/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ContinueButtonProps {}

const ContinueButton: React.FC<ContinueButtonProps> = () => {
  return (
    <div className="flex flex-col justify-center items-start px-4 py-3 w-full text-sm font-bold text-center whitespace-nowrap text-slate-50 max-md:pr-5 max-md:max-w-full">
      <button type="submit" className="px-4 py-2.5 bg-sky-500 rounded-xl">
        Continue
      </button>
    </div>
  );
};

export default ContinueButton;