/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ProfilePhotoProps {}

const ProfilePhoto: React.FC<ProfilePhotoProps> = () => {
  return (
    <section className="flex flex-col items-center p-4 w-full text-2xl font-bold text-center max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/046f4e694242b8d4c609b691093d7a63e8665a3107c5787596f75a8fd7054c6a?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e"
        alt=""
        className="w-32 max-w-full aspect-square rounded-[64px]"
      />
      <h2 className="mt-4">Add a profile photo</h2>
    </section>
  );
};

export default ProfilePhoto;