/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProfilePhoto from "./ProfilePhoto";
import FormField from "./FormField";
import ContinueButton from "./ContinueButton";

interface CommunityFormProps {}

const CommunityForm: React.FC<CommunityFormProps> = () => {
  return (
    <main className="flex flex-col py-5 text-base max-w-[960px] text-zinc-900">
      <header className="px-4 pt-6 pb-3 text-3xl font-bold text-center max-md:max-w-full">
        Unéte a la comunidad de tutorías de la UAM
      </header>
      <p className="px-4 pt-1 pb-3 text-center max-md:max-w-full">
        Cuéntanos sobre ti
      </p>
      <ProfilePhoto />
      <form>
        <ContinueButton />
      </form>
    </main>
  );
};

export default CommunityForm;
