/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const DatePicker: React.FC = () => {
  const days = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
  const dates = Array.from({ length: 30 }, (_, i) => i + 1);

  return (
    <section className="w-full max-w-[960px]">
      <h2 className="px-4 pt-5 pb-3 text-2xl font-bold text-neutral-900">
        Elige una fecha
      </h2>
      <div className="flex flex-col items-center p-4 text-sm font-medium text-neutral-900">
        <div className="flex gap-3 justify-between items-start p-1 max-w-full text-base font-bold text-center w-[336px]">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/66d19c5e03fa1bcedc4c4b79cde6ee756e11f70fae81602033036b8bb23a6e04?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e" alt="Previous month" className="shrink-0 aspect-square w-[18px]" />
          <div className="self-stretch">September 2023</div>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d2f76ff7dc28af284d1da6dbb8cc83def830eb6a391faecd63675877566bee78?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e" alt="Next month" className="shrink-0 aspect-square w-[18px]" />
        </div>
        <div className="flex max-w-full text-sm font-bold whitespace-nowrap w-[336px]">
          {days.map((day, index) => (
            <div key={index} className="px-5 pt-3.5 pb-0.5">{day}</div>
          ))}
        </div>
        <div className="grid grid-cols-7 gap-5 px-5 max-w-full text-center whitespace-nowrap w-[336px]">
          {dates.map((date, index) => (
            <div
              key={index}
              className={`py-3.5 ${date === 5 ? 'px-5 h-12 text-white bg-blue-600 rounded-3xl' : ''}`}
            >
              {date}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default DatePicker;