/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col self-center px-5 pt-10 pb-2 w-full text-base text-center max-w-[960px] text-slate-500 max-md:max-w-full">
      <nav className="flex justify-center items-center px-16 max-md:px-5 max-md:max-w-full">
        <div className="flex gap-px">
          <a href="#about">Acerca de nosotros</a>
          <a href="#faq">Preguntas frecuentes</a>
        </div>
      </nav>
      <div className="mt-6 max-md:max-w-full">
        © 2023 Tutor, Inc. All rights reserved
      </div>
    </footer>
  );
};

export default Footer;