/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Header: React.FC = () => {
  return (
    <header className="flex justify-between px-10 py-3 border-b border-gray-200 text-neutral-900 max-md:flex-wrap max-md:px-5">
      <div className="flex gap-4 my-auto text-lg font-bold">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/559240774ca61a648e61a63939052e484c6b01defefb1d35aac35f1d6e1ff8d5?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e" alt="" className="shrink-0 self-start w-5 aspect-square" />
        <div>Tutor UAM</div>
      </div>
      <nav className="flex flex-1 gap-5 pl-20 text-sm font-medium max-md:flex-wrap">
        <div className="my-auto">Encontrar tutor</div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/a7fdcc33c614fe390b2f654f356f5854c917ae39e300f56b084ca55a6ff8a9b8?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e" alt="User profile" className="shrink-0 w-10 rounded-3xl aspect-square" />
      </nav>
    </header>
  );
};

export default Header;