/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const SubjectSelector: React.FC = () => {
  return (
    <section className="w-full max-w-[960px]">
      <h2 className="px-4 pt-4 pb-2 text-2xl font-bold text-neutral-900">
        Escoger materia
      </h2>
      <div className="flex flex-col justify-center items-start p-3 text-sm font-medium text-center whitespace-nowrap text-neutral-900">
        <div className="flex gap-2 justify-center py-1.5 pr-2 pl-4 bg-gray-100 rounded-xl max-md:px-5">
          <div>Materia</div>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6b83fee56b61632f31397cce247276ef73952b929fdbc0b61db90252ba9199e?apiKey=d014db5933b042d7872678898cc44b5e&&apiKey=d014db5933b042d7872678898cc44b5e" alt="" className="flex-1 shrink-0 self-start w-full aspect-square" />
        </div>
      </div>
    </section>
  );
};

export default SubjectSelector;