/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import SubjectSelector from './SubjectSelector';
import DatePicker from './DatePicker';
import TimePicker from './TimePicker';
import Footer from './Footer';

const TutorUAM: React.FC = () => {
  return (
    <div className="flex flex-col pb-8 bg-white">
      <Header />
      <main className="flex flex-col items-center px-20 pt-2.5 w-full max-md:px-5 max-md:max-w-full">
        <h1 className="p-4 max-w-full text-3xl font-bold text-neutral-900 w-[960px] max-md:pr-5 max-md:max-w-full">
          Encuentra un tutor en Inglés
        </h1>
        <SubjectSelector />
        <DatePicker />
        <TimePicker />
      </main>
      <Footer />
    </div>
  );
};

export default TutorUAM;